name: code scan

on:
  workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID:
        required: true
        type: string         
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string       
      AWS_SESSION_TOKEN:
        required: false
        type: string            
         
jobs:
  Code-Scan:
    runs-on: ubuntu-latest
    steps:    
      - name: scan
        run: |
          docker run  --rm -v ${PWD}:/prowler/output --name prowler --env ${{inputs.AWS_ACCESS_KEY_ID}} --env ${{inputs.AWS_SECRET_ACCESS_KEY}} --env ${{inputs.AWS_SESSION_TOKEN}} docker pull gcr.io/xenon-container-350901/prowler:latest -r us-east-2 -f us-east-2 -M csv,json,html -c check32
          ls -al
          pwd    
