name: code scan

on:
  workflow_call:
    inputs:
      SCAN-TYPE:
        required: true
        type: string
      SCAN-BASEDIR:
        required: false
        type: string  
      SCAN-INCLUDE:
        required: false
        type: string       
      SCAN-EXCLUDE:
        required: false
        type: string            
    secrets:
      SONAR_TOKEN:
        required: true       
      SONAR_HOST_URL:
        required: true          
jobs:
  Code-Scan:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
        
    - name: IaC KICS scan
      if: contains(inputs.SCAN-TYPE, 'IaC')
      working-directory: ${{inputs.SCAN-BASEDIR}}
      run: |
        docker run -v $PWD:/path checkmarx/kics scan -p "/path" -o "/path" --report-formats "sonarqube" --ignore-on-exit "all"
        #if [ -z ${{inputs.SCAN-OUTPUT}} ]; then export output="iac-output.json";  else export output=${{inputs.SCAN-OUTPUT}}; fi
        sed "s/..\/..\/path\///g" sonarqube-results.json > IaC.report

    - name: set sonarqube args
      run: |
        echo "SCAN-TYPE=${{inputs.SCAN-TYPE}}"  >> $GITHUB_ENV
        echo "REPORTS-PATHS=${SCAN-TYPE//,/.report,}.report" >> $GITHUB_ENV
        
    - name: test
      run: |
        echo ${{env.REPORTS-PATHS}}
        
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: ${{inputs.SCAN-BASEDIR}}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        args: >
          -Dsonar.projectKey=${{ github.event.repository.name }}
          -Dsonar.externalIssuesReportPaths=${{env.REPORTS-PATHS}}
          -Dsonar.sources=${{inputs.SCAN-INCLUDE}}
          -Dsonar.exclusions=${{inputs.SCAN-EXCLUDE}}
