name: code scan

on:
  workflow_call:
    inputs:
      SCAN_TYPE:
        required: true
        type: string         
      SCAN_INCLUDE:
        required: true
        type: string       
      SCAN_EXCLUDE:
        required: false
        type: string            
         
jobs:
  Code-Scan:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    
    - name: IaC KICS scan
      if: contains(inputs.SCAN_TYPE, 'IaC')
      run: |
        if [ -z ${{inputs.SCAN_EXCLUDE}} ]; then export arg="";  else export arg="--exclude-paths ${{inputs.SCAN_EXCLUDE}}"; fi
        docker run -v $PWD:/path checkmarx/kics scan -p "/path" -o "/path" --path ${{inputs.SCAN_INCLUDE}} --report-formats "sonarqube" --ignore-on-exit "all"
        #if [ -z ${{inputs.SCAN-OUTPUT}} ]; then export output="iac-output.json";  else export output=${{inputs.SCAN-OUTPUT}}; fi
        sed "s/..\/..\/path\///g" sonarqube-results.json > external_report
        
        
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        args: >
          -Dsonar.projectKey=test #"${{ github.event.repository.name }}-${{inputs.SCAN_TYPE}}"
          -Dsonar.externalIssuesReportPaths=external_report
          -Dsonar.sources=${{inputs.SCAN_INCLUDE}}
          -Dsonar.exclusions=${{inputs.SCAN_EXCLUDE}}
