name: code scan

on:
  workflow_call:
    inputs:
      SCAN-TYPE:
        required: true
        type: string
      SCAN-BASEDIR:
        required: false
        type: string  
      SCAN-INCLUDE:
        required: false
        type: string       
      SCAN-EXCLUDE:
        required: false
        type: string            
    secrets:
      SONAR_TOKEN:
        required: true       
      SONAR_HOST_URL:
        required: true          
jobs:
  Code-Scan:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
        

    - name: set sonarqube args
      run: |
        echo "SCAN-TYPE=${{inputs.SCAN-TYPE}}"  >> $GITHUB_ENV
        echo env.SCAN-TYPE
        echo "${env.SCAN-TYPE//,/.report,}".report
        echo REPORTS-PATHS="${env.SCAN-TYPE//,/.report,}".report
        echo REPORTS-PATHS="${env.SCAN-TYPE//,/.report,}".report >> $GITHUB_ENV
        
    - name: test
      run: |
        echo ${{env.REPORTS-PATHS}}
        

