name: Infracost Workflow

on:
  workflow_call:
    secrets:
      INFRACOST_API_KEY:
        required: true 
      CONFLUENCE_USERNAME:
        required: true     
      CONFLUENCE_API_TOKEN:
        required: true
    inputs:
      CONFLUENCE_PAGE_ID:
        required: true
        type: string  
      CONFLUENCE_PAGE_TITLE:
        required: true
        type: string 
      INFRACOST_ARTIFACT:
        required: true
        type: string 
        
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout
jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.INFRACOST_ARTIFACT }} 
    
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost cost estimate
        run: |
            pwd
            ls -al
            infracost breakdown --config-file infracost.yml --format json --out-file output.json
            ls -al ${GITHUB_WORKSPACE}/output.json
 
      - name: Checkout shared repo
        continue-on-error: true
        run: |
          git clone https://github.com/poc-lycbrina/.github script
          pwd
          ls -al
        
      - name: post result to conflunece
        working-directory: script/.github/workflows/scripts/infracost
        run: |
            cat << EOF > .env
            LOG_LEVEL=INFO
            DATA_FILE= ${GITHUB_WORKSPACE}/output.json
            URL=https://lycbrian.atlassian.net/
            USERNAME=${{ inputs.CONFLUENCE_USERNAME }} 
            API_TOKEN=${{ inputs.CONFLUENCE_API_TOKEN }} 
            PAGE_ID=${{ inputs.CONFLUENCE_PAGE_ID }} 
            PAGE_TITLE=${{ inputs.CONFLUENCE_PAGE_TITLE }} 
            EOF
            cat .env
            pip3 install -r requirements.txt
            python3 infracost.py
